language: node_js
node_js:
  - "node"
script:
  # run generator
  - npx eleventy
  # create .nojekyll files
  # We are telling GitHub to not process this branch using jekyll
  - touch .nojekyll
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
